---
- hosts: all
  vars:
    hadoop_version: hadoop-2.7.1
    hadoop_install_dir: /usr/local/lib/{{hadoop_version}}
  tasks:
    - name: Add the Java 8 repository
      sudo: yes
      apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" update_cache=yes state=present

    - name: Add the Java 8 source repository
      sudo: yes
      apt_repository: repo="deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" update_cache=yes state=present

    - name: Add the key
      sudo: yes
      apt_key: keyserver="keyserver.ubuntu.com" id="EEA14886" state=present

    - name: Add webupd8team repository
      sudo: yes
      apt_repository: repo="ppa:webupd8team/java" update_cache=yes state=present

    - name: Deal with Oracle Java 8 Licensing Bullshit
      sudo: yes
      shell: "echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections"

    - name: Ensure packages setup and ready
      sudo: yes
      apt:  name={{item}} state=present update_cache=yes
      with_items:
        - ssh
        - rsync
        - oracle-java8-installer
        - oracle-java8-set-default

    - name: Generate the hadoop profile.d system variables
      sudo: yes
      template: src="templates/etc/profile.d/hadoop.sh.j2" dest="/etc/profile.d/hadoop.sh"

    - name: Get Hadoop 2.7.1 release from remote servers
      get_url: url="http://www.us.apache.org/dist/hadoop/common/{{hadoop_version}}/{{hadoop_version}}.tar.gz" dest="/tmp/{{hadoop_version}}.tar.gz"

    - name: Untar the Hadoop release
      sudo: yes
      unarchive: src="/tmp/{{hadoop_version}}.tar.gz" dest="/usr/local/lib/" copy=no

    - name: Copy hadoop core-site xml file
      sudo: yes
      template: src="templates{{hadoop_install_dir}}/etc/hadoop/{{item}}.j2"  dest="{{hadoop_install_dir}}/etc/hadoop/{{item}}" mode="0644"
      with_items:
        - core-site.xml
        - hdfs-site.xml

    - name: Generate an SSH key for the user
      sudo: yes
      user: name={{ansible_env.USER}} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa ssh_key_comment="{{ansible_env.USER}}@localhost}}"

    - name: cat file contents of the rsa key into variable
      shell: cat /home/{{ansible_env.USER}}/.ssh/id_rsa.pub
      register: ssh_key_contents

    - name: Add the rsa key for the user to the authorized keys file
      authorized_key: user={{ansible_env.USER}} key="{{ssh_key_contents.stdout}}" state=present

    - name: Create the hadoop log directory
      sudo: yes
      file: path="{{hadoop_install_dir}}/logs" state=directory mode=0666

    - name: Get the JAVA_HOME for the system
      shell: source /etc/profile.d/jdk.sh && echo $JAVA_HOME
      args:
        executable: /bin/bash
      register: java_home

    - name: This line in the hadoop conf does not seem to work due to the environment. Temp fix.
      sudo: yes
      lineinfile: dest="{{hadoop_install_dir}}/etc/hadoop/hadoop-env.sh" line="export JAVA_HOME={{java_home.stdout}}" regexp="export JAVA_HOME=\${JAVA_HOME}"
